branch-defaults:
  main:
    environment: Choccy-env
environment-defaults:
  Choccy-env:
    branch: null
    repository: null
global:
  application_name: choccy
  default_ec2_keyname: null
  default_platform: Node.js 12 running on 64bit Amazon Linux 2
  default_region: ap-southeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
