version: 2.1
jobs:
  build:
    docker:
        - image: 'circleci/node'
    steps:
      - checkout
      - restore_cache:
          name: Restore yarn package cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    docker:
      - image: 'circleci/python'
    steps:
      - attach_workspace:
          at: .
      - run: pip install awsebcli
      - run: eb deploy

workflows:
  workflow:
    jobs:
      - build
      - hold:
          filters:
            branches:
              only:
                - main
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - hold
