version: 2.1
jobs:
  build:
    working_directory: ~/project
    docker:
        - image: 'circleci/node'
    steps:
      - checkout
      - run: yarn install
      - run: yarn build
  deploy:
    working_directory: ~/project
    docker:
      - image: 'circleci/python'
    steps:
      - run: pip install awsebcli
      - run: eb use Choccy-env
      - run: eb deploy

workflows:
  workflow:
    jobs:
      - build
      - deploy:
          requires:
            - build
